server:
  port: 8080
spring:

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: eventsstream
          group: myGroupStream
        messageChannel:
          destination: eventsstream
          content-type: application/json
        subscribableChannel:
          destination: eventsstream
